#!/usr/bin/env bash
# =============================================================================
# nkp-deploy.sh — NKP 2.17 Air-Gapped Pre-Provisioned Cluster
# 3 Control Planes · 0 Workers · Trimmed Kommander
#
# USAGE
#   1. Edit the CONFIG section below
#   2. On the bootstrap node:  bash nkp-deploy.sh
#
# Idempotent — safe to re-run; each phase checks state before acting.
# Ref: NKP 2.17 pre-provisioned / air-gapped docs
# =============================================================================
set -euo pipefail

# =============================================================================
# CONFIG — edit this section before running
# =============================================================================

CLUSTER_NAME="nkp-airgap"

# ── Node IPs ─────────────────────────────────────────────────────────────────
# BOOTSTRAP_IP is also CP1. Run this script on that node.
BOOTSTRAP_IP="192.168.1.159"
CP_IPS=(
  "192.168.1.159"   # CP1 — bootstrap node
  "192.168.1.158"   # CP2
  "192.168.1.156"   # CP3
)

# ── SSH ───────────────────────────────────────────────────────────────────────
SSH_USER="ice"
SSH_KEY="$HOME/.ssh/nkp_rsa"    # generated by this script if absent
SSH_PASS='***REMOVED***'          # used once for initial key distribution only

# ── Control Plane VIP (kube-vip) ─────────────────────────────────────────────
# A free IP on your LAN that floats across the 3 CP nodes.
CONTROL_PLANE_VIP="192.168.1.200"   # ← set a free LAN IP
CONTROL_PLANE_PORT=6443

# ── MetalLB LoadBalancer pool ─────────────────────────────────────────────────
LB_IP_RANGE="192.168.1.201-192.168.1.210"   # ← set a free range

# ── Air-gapped registry ───────────────────────────────────────────────────────
REGISTRY_URL="https://registry.local:5000"       # ← your local registry
REGISTRY_CACERT="/etc/ssl/certs/registry-ca.crt" # ← CA cert path on bootstrap

# Source registries to mirror through the local registry
MIRROR_REGISTRIES=(
  "docker.io"
  "registry.k8s.io"
  "quay.io"
  "gcr.io"
  "ghcr.io"
)

# =============================================================================
# END CONFIG
# =============================================================================

# ── Derived paths ─────────────────────────────────────────────────────────────
KUBECONFIG_BOOTSTRAP="$HOME/.kube/nkp-bootstrap.kubeconfig"
KUBECONFIG_CLUSTER="$HOME/.kube/${CLUSTER_NAME}.kubeconfig"

# ── Logging ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
log()  { echo -e "${GREEN}[NKP]${NC} $*"; }
step() { echo -e "\n${CYAN}${BOLD}═══ $* ${NC}"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
die()  { echo -e "${RED}[ERR]${NC} $*" >&2; exit 1; }

ssh_node() {
  local ip=$1; shift
  ssh -o StrictHostKeyChecking=no -o ConnectTimeout=15 \
      -o ServerAliveInterval=30 \
      -i "$SSH_KEY" "$SSH_USER@$ip" "$@"
}

# =============================================================================
# Phase 0 — Preflight
# =============================================================================
phase0_preflight() {
  step "Phase 0: Preflight"
  command -v nkp     >/dev/null || die "nkp CLI not found — install it first"
  command -v kubectl >/dev/null || die "kubectl not found — install it first"
  command -v helm    >/dev/null || warn "helm not found — may be needed for Kommander"
  mkdir -p "$HOME/.kube"
  [[ -f "$REGISTRY_CACERT" ]] || warn "CA cert not found: $REGISTRY_CACERT — set REGISTRY_URL to http:// if using insecure registry"
  log "Cluster  : $CLUSTER_NAME"
  log "VIP      : $CONTROL_PLANE_VIP:$CONTROL_PLANE_PORT"
  log "Nodes    : ${CP_IPS[*]}"
  log "Registry : $REGISTRY_URL"
}

# =============================================================================
# Phase 1 — SSH key generation and distribution
# =============================================================================
phase1_ssh_keys() {
  step "Phase 1: SSH key setup"

  # sshpass is needed only for initial key distribution
  if ! command -v sshpass &>/dev/null; then
    log "Installing sshpass..."
    sudo apt-get install -y -q sshpass || die "Cannot install sshpass — run: apt-get install -y sshpass"
  fi

  # Generate a dedicated deploy key if it doesn't exist
  if [[ ! -f "$SSH_KEY" ]]; then
    ssh-keygen -t rsa -b 4096 -f "$SSH_KEY" -N "" -C "nkp-deploy" -q
    log "Generated $SSH_KEY"
  else
    log "SSH key exists — skipping generation"
  fi

  # Copy key to every node — ssh-copy-id won't add duplicate entries
  for ip in "${CP_IPS[@]}"; do
    log "  → $ip"
    sshpass -p "$SSH_PASS" ssh-copy-id \
      -o StrictHostKeyChecking=no \
      -i "${SSH_KEY}.pub" \
      "$SSH_USER@$ip" 2>/dev/null \
    && log "    ✓" \
    || warn "    key copy returned non-zero (already installed or wrong password)"
  done
}

# =============================================================================
# Phase 2 — Node prerequisites on all CP nodes
# =============================================================================
phase2_node_prereqs() {
  step "Phase 2: Node prerequisites"

  for ip in "${CP_IPS[@]}"; do
    log "  Configuring $ip..."
    ssh_node "$ip" bash -s -- \
      "$REGISTRY_URL" "$REGISTRY_CACERT" "${MIRROR_REGISTRIES[@]}" <<'REMOTE'
set -e
MIRROR_SERVER="$1"; shift
MIRROR_CA="$1";     shift
REGISTRIES=("$@")

# ── disable swap ──────────────────────────────────────────────────────────────
swapoff -a 2>/dev/null || true
sed -i -E '/^[^#].*[[:space:]]swap[[:space:]]/s/^/#/' /etc/fstab

# ── kernel modules ────────────────────────────────────────────────────────────
cat > /etc/modules-load.d/nkp-k8s.conf <<'EOF'
overlay
br_netfilter
EOF
modprobe overlay      2>/dev/null || true
modprobe br_netfilter 2>/dev/null || true

# ── sysctl ────────────────────────────────────────────────────────────────────
cat > /etc/sysctl.d/99-nkp-k8s.conf <<'EOF'
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
fs.inotify.max_user_instances       = 8192
fs.inotify.max_user_watches         = 1048576
vm.overcommit_memory                = 1
EOF
sysctl --system >/dev/null 2>&1

# ── containerd: enable SystemdCgroup ─────────────────────────────────────────
mkdir -p /etc/containerd
if ! grep -q "SystemdCgroup = true" /etc/containerd/config.toml 2>/dev/null; then
  containerd config default 2>/dev/null > /etc/containerd/config.toml
  sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
fi

# ── containerd: registry mirrors (containerd v2.x hosts.toml format) ─────────
# Each upstream registry gets a hosts.toml pointing at the local mirror.
CERTS_DIR="/etc/containerd/certs.d"
mkdir -p "$CERTS_DIR"

for reg in "${REGISTRIES[@]}"; do
  mkdir -p "$CERTS_DIR/$reg"
  {
    echo "server = \"${MIRROR_SERVER}\""
    echo ""
    echo "[host.\"${MIRROR_SERVER}\"]"
    echo "  capabilities = [\"pull\", \"resolve\"]"
    if [[ -f "$MIRROR_CA" ]]; then
      echo "  ca = [\"${MIRROR_CA}\"]"
    else
      echo "  skip_verify = true"
    fi
  } > "$CERTS_DIR/$reg/hosts.toml"
done

# ── containerd config: set config_path for hosts.toml to take effect ─────────
if ! grep -q "config_path" /etc/containerd/config.toml 2>/dev/null; then
  sed -i '/\[plugins."io.containerd.grpc.v1.cri".registry\]/a\      config_path = "/etc/containerd/certs.d"' \
    /etc/containerd/config.toml 2>/dev/null || true
fi

systemctl enable containerd  >/dev/null 2>&1 || true
systemctl restart containerd

echo "✓ $(hostname) ready"
REMOTE
    log "    ✓ $ip"
  done
}

# =============================================================================
# Phase 3 — Docker on bootstrap node (needed for kind bootstrap cluster)
# =============================================================================
phase3_docker_bootstrap() {
  step "Phase 3: Docker on bootstrap node"
  if command -v docker &>/dev/null && docker info &>/dev/null 2>&1; then
    log "Docker already running — skipping"
    return
  fi
  log "Installing Docker CE..."
  apt-get install -y -q ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -q
  apt-get install -y -q docker-ce docker-ce-cli containerd.io docker-buildx-plugin
  usermod -aG docker "$USER" || true
  systemctl enable --now docker >/dev/null 2>&1
  log "✓ Docker installed"

  # In air-gapped environments: load NKP bootstrap images from bundle if present
  if [[ -f "$HOME/nkp-air-bundle.tar.gz" ]]; then
    log "Loading bootstrap images from bundle..."
    nkp push bundle --bundle "$HOME/nkp-air-bundle.tar.gz" \
      --to-registry "$REGISTRY_URL" 2>/dev/null || \
    warn "Bundle push failed — ensure images are in $REGISTRY_URL before continuing"
  else
    warn "No air-gapped bundle found at ~/nkp-air-bundle.tar.gz — skipping image push"
    warn "Ensure all NKP images are already in $REGISTRY_URL"
  fi
}

# =============================================================================
# Phase 4 — NKP bootstrap cluster (kind)
# =============================================================================
phase4_bootstrap() {
  step "Phase 4: NKP bootstrap cluster"
  if [[ -f "$KUBECONFIG_BOOTSTRAP" ]] && \
     kubectl --kubeconfig "$KUBECONFIG_BOOTSTRAP" get nodes &>/dev/null 2>&1; then
    log "Bootstrap cluster already running — skipping"
  else
    nkp create bootstrap \
      --kubeconfig "$KUBECONFIG_BOOTSTRAP"
    log "✓ Bootstrap cluster ready"
  fi
}

# =============================================================================
# Phase 5 — PreprovisionedInventory (register CP node IPs into bootstrap)
# =============================================================================
phase5_inventory() {
  step "Phase 5: Node inventory"
  export KUBECONFIG="$KUBECONFIG_BOOTSTRAP"

  SSH_PUBKEY=$(cat "${SSH_KEY}.pub")
  local idx=0

  for ip in "${CP_IPS[@]}"; do
    local name="${CLUSTER_NAME}-cp-${idx}"

    if kubectl get preprovisionedinventory "$name" -n default &>/dev/null 2>&1; then
      log "  $name already registered — skipping"
    else
      kubectl apply -f - <<EOF
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: PreprovisionedInventory
metadata:
  name: ${name}
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
spec:
  url: ${ip}
  sshAuthorizedKeys:
    - "${SSH_PUBKEY}"
EOF
      log "  ✓ Registered $ip → $name"
    fi
    idx=$((idx + 1))
  done
}

# =============================================================================
# Phase 6 — Create NKP cluster
# =============================================================================
phase6_create_cluster() {
  step "Phase 6: Create NKP cluster"
  export KUBECONFIG="$KUBECONFIG_BOOTSTRAP"

  if kubectl get cluster "$CLUSTER_NAME" -n default &>/dev/null 2>&1; then
    log "Cluster $CLUSTER_NAME already exists — skipping"
    return
  fi

  local cacert_arg=()
  [[ -f "$REGISTRY_CACERT" ]] && cacert_arg=(--registry-mirror-cacert "$REGISTRY_CACERT")

  nkp create cluster preprovisioned \
    --cluster-name             "$CLUSTER_NAME" \
    --control-plane-endpoint-host "$CONTROL_PLANE_VIP" \
    --control-plane-endpoint-port "$CONTROL_PLANE_PORT" \
    --control-plane-replicas   3 \
    --worker-replicas          0 \
    --ssh-username             "$SSH_USER" \
    --ssh-private-key-file     "$SSH_KEY" \
    --registry-mirror-url      "$REGISTRY_URL" \
    "${cacert_arg[@]}" \
    --self-managed \
    --kubeconfig "$KUBECONFIG_BOOTSTRAP"

  log "✓ Cluster manifest applied"
}

# =============================================================================
# Phase 7 — Wait for cluster + export kubeconfig
# =============================================================================
phase7_wait() {
  step "Phase 7: Waiting for cluster (15-40 min depending on image pull speed)"
  export KUBECONFIG="$KUBECONFIG_BOOTSTRAP"

  if nkp wait cluster "$CLUSTER_NAME" \
       --namespace default \
       --timeout 60m \
       --kubeconfig "$KUBECONFIG_BOOTSTRAP" 2>/dev/null; then
    log "✓ nkp wait cluster complete"
  else
    # Fallback: watch CAPI cluster condition
    log "nkp wait unavailable — using kubectl watch (60m timeout)..."
    kubectl wait cluster "$CLUSTER_NAME" \
      -n default \
      --for=condition=Ready \
      --timeout=60m
  fi

  nkp get kubeconfig "$CLUSTER_NAME" \
    --namespace default \
    --kubeconfig "$KUBECONFIG_BOOTSTRAP" \
    > "$KUBECONFIG_CLUSTER"
  chmod 600 "$KUBECONFIG_CLUSTER"
  log "✓ Kubeconfig: $KUBECONFIG_CLUSTER"
}

# =============================================================================
# Phase 8 — Untaint control planes (required when no workers exist)
# =============================================================================
phase8_untaint_cp() {
  step "Phase 8: Untaint control plane nodes"
  export KUBECONFIG="$KUBECONFIG_CLUSTER"

  while IFS= read -r node; do
    kubectl taint node "$node" \
      node-role.kubernetes.io/control-plane:NoSchedule- \
      2>/dev/null \
    && log "  Untainted $node" \
    || log "  $node — taint already absent"
  done < <(kubectl get nodes -o name | sed 's|node/||')
}

# =============================================================================
# Phase 9 — MetalLB IP address pool
# =============================================================================
phase9_metallb() {
  step "Phase 9: MetalLB IP pool ($LB_IP_RANGE)"
  export KUBECONFIG="$KUBECONFIG_CLUSTER"

  if kubectl get ipaddresspool -n metallb-system nkp-pool &>/dev/null 2>&1; then
    log "MetalLB pool already configured — skipping"
    return
  fi

  kubectl apply -f - <<EOF
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nkp-pool
  namespace: metallb-system
spec:
  addresses:
    - ${LB_IP_RANGE}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: nkp-l2
  namespace: metallb-system
EOF
  log "✓ MetalLB pool applied"
}

# =============================================================================
# Phase 10 — Kommander trimmed install
# =============================================================================
phase10_kommander() {
  step "Phase 10: Kommander (trimmed)"
  export KUBECONFIG="$KUBECONFIG_CLUSTER"

  if kubectl get namespace kommander &>/dev/null 2>&1; then
    log "Kommander already installed — skipping"
    return
  fi

  # Only the core management apps; monitoring/logging/velero disabled.
  # Add entries here as needed for your environment.
  cat > /tmp/kommander-config.yaml <<'EOF'
apiVersion: config.kommander.mesosphere.io/v1alpha1
kind: Installation
metadata:
  name: kommander
spec:
  apps:
    # ── core (keep) ──────────────────────────────────────────
    kommander:
      enabled: true
    cert-manager:
      enabled: true
    traefik:
      enabled: true
    dex:
      enabled: true
    dex-k8s-authenticator:
      enabled: true
    # ── trimmed (disabled) ───────────────────────────────────
    kube-prometheus-stack:
      enabled: false
    grafana-logging:
      enabled: false
    loki-distributed:
      enabled: false
    velero:
      enabled: false
    karma-dashboard:
      enabled: false
    kubernetes-dashboard:
      enabled: false
    centralized-grafana:
      enabled: false
    prometheus-adapter:
      enabled: false
EOF

  nkp install kommander \
    --installer-config /tmp/kommander-config.yaml \
    --kubeconfig "$KUBECONFIG_CLUSTER"

  log "✓ Kommander installed"
}

# =============================================================================
# Phase 11 — Teardown bootstrap (cleanup after self-managed pivot)
# =============================================================================
phase11_teardown_bootstrap() {
  step "Phase 11: Teardown bootstrap cluster"
  if [[ ! -f "$KUBECONFIG_BOOTSTRAP" ]]; then
    log "Bootstrap kubeconfig gone — already torn down"
    return
  fi
  if kubectl --kubeconfig "$KUBECONFIG_BOOTSTRAP" \
       get cluster "$CLUSTER_NAME" -n default &>/dev/null 2>&1; then
    log "Cluster still on bootstrap — skipping teardown (pivot not complete yet?)"
    return
  fi
  nkp delete bootstrap \
    --kubeconfig "$KUBECONFIG_BOOTSTRAP" 2>/dev/null || true
  rm -f "$KUBECONFIG_BOOTSTRAP"
  log "✓ Bootstrap torn down"
}

# =============================================================================
# Phase 12 — Verify
# =============================================================================
phase12_verify() {
  step "Phase 12: Verify"
  export KUBECONFIG="$KUBECONFIG_CLUSTER"

  echo ""
  kubectl get nodes -o wide
  echo ""
  echo "Unhealthy pods (if any):"
  kubectl get pods -A --field-selector='status.phase!=Running,status.phase!=Succeeded' \
    2>/dev/null | head -20 || true

  echo ""
  log "✓ Deployment complete"
  log ""
  log "  Kubeconfig : export KUBECONFIG=$KUBECONFIG_CLUSTER"
  log "  Dashboard  : https://${CONTROL_PLANE_VIP}/dkp/kommander/dashboard"
  log ""

  local creds
  creds=$(kubectl -n kommander get secret dkp-credentials \
    -o jsonpath='{.data.password}' 2>/dev/null | base64 -d 2>/dev/null) || true
  if [[ -n "$creds" ]]; then
    log "  Admin pass : $creds"
  else
    log "  Admin pass : run 'nkp get dashboard --kubeconfig $KUBECONFIG_CLUSTER'"
  fi
}

# =============================================================================
# Main
# =============================================================================
main() {
  echo ""
  echo -e "${CYAN}${BOLD}╔══════════════════════════════════════════════════════╗"
  echo -e "║  NKP 2.17 — Air-Gapped 3-CP / 0-Worker Deploy       ║"
  echo -e "╚══════════════════════════════════════════════════════╝${NC}"
  echo ""

  phase0_preflight
  phase1_ssh_keys
  phase2_node_prereqs
  phase3_docker_bootstrap
  phase4_bootstrap
  phase5_inventory
  phase6_create_cluster
  phase7_wait
  phase8_untaint_cp
  phase9_metallb
  phase10_kommander
  phase11_teardown_bootstrap
  phase12_verify
}

main "$@"
