#!/usr/bin/env bash
# =============================================================================
# nkp-deploy.sh — NKP 2.17 Air-Gapped Pre-Provisioned Cluster
# 3 Control Planes · 0 Workers · Trimmed Kommander
#
# USAGE
#   1. Edit the CONFIG section below
#   2. On the bootstrap node:  bash nkp-deploy.sh
#
# Idempotent — safe to re-run; each phase checks state before acting.
# Ref: NKP 2.17 pre-provisioned / air-gapped docs
# =============================================================================
set -euo pipefail

# =============================================================================
# CONFIG — edit this section before running
# =============================================================================

CLUSTER_NAME="nkp-airgap"

# ── Node IPs ─────────────────────────────────────────────────────────────────
# BOOTSTRAP_IP is also CP1. Run this script on that node.
BOOTSTRAP_IP="192.168.1.159"
CP_IPS=(
  "192.168.1.159"   # CP1 — bootstrap node
  "192.168.1.158"   # CP2
  "192.168.1.156"   # CP3
)

# ── SSH ───────────────────────────────────────────────────────────────────────
SSH_USER="ice"
SSH_KEY="$HOME/.ssh/nkp_rsa"    # generated by this script if absent
SSH_PASS='***REMOVED***'          # used once for initial key distribution only

# ── Control Plane VIP (kube-vip) ─────────────────────────────────────────────
# A free IP on your LAN that floats across the 3 CP nodes.
CONTROL_PLANE_VIP="192.168.1.200"   # ← set a free LAN IP
CONTROL_PLANE_PORT=6443

# ── MetalLB LoadBalancer pool ─────────────────────────────────────────────────
LB_IP_RANGE="192.168.1.201-192.168.1.210"   # ← set a free range

# ── Air-gapped registry ───────────────────────────────────────────────────────
# IP:port (no scheme) — used for nkp push bundle --to-registry
REGISTRY_IP="192.168.1.159:5000"
# https:// URL — used for nkp create cluster/bootstrap --registry-mirror-url
REGISTRY_MIRROR_URL="https://192.168.1.159:5000"

# ── NKP bundle (extracted tarball) ────────────────────────────────────────────
BUNDLE_DIR="$HOME/nkp-bundle/nkp-v2.17.1"
KONVOY_BUNDLE="$BUNDLE_DIR/container-images/konvoy-image-bundle-v2.17.1.tar"
KOMMANDER_BUNDLE="$BUNDLE_DIR/container-images/kommander-image-bundle-v2.17.1.tar"

# =============================================================================
# END CONFIG
# =============================================================================

# ── Derived paths ─────────────────────────────────────────────────────────────
KUBECONFIG_BOOTSTRAP="$HOME/.kube/nkp-bootstrap.kubeconfig"
KUBECONFIG_CLUSTER="$HOME/.kube/${CLUSTER_NAME}.kubeconfig"

# ── Logging ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
log()  { echo -e "${GREEN}[NKP]${NC} $*"; }
step() { echo -e "\n${CYAN}${BOLD}═══ $* ${NC}"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
die()  { echo -e "${RED}[ERR]${NC} $*" >&2; exit 1; }

ssh_node() {
  local ip=$1; shift
  ssh -o StrictHostKeyChecking=no -o ConnectTimeout=15 \
      -o ServerAliveInterval=30 \
      -i "$SSH_KEY" "$SSH_USER@$ip" "$@"
}

# =============================================================================
# Phase 0 — Preflight
# =============================================================================
phase0_preflight() {
  step "Phase 0: Preflight"
  command -v nkp     >/dev/null || die "nkp CLI not found — install it first"
  command -v kubectl >/dev/null || die "kubectl not found — install it first"
  command -v docker  >/dev/null || die "docker not found — must be pre-installed (air-gapped)"
  [[ -f "$KONVOY_BUNDLE" ]]    || die "Konvoy bundle not found: $KONVOY_BUNDLE"
  [[ -f "$KOMMANDER_BUNDLE" ]] || die "Kommander bundle not found: $KOMMANDER_BUNDLE"
  mkdir -p "$HOME/.kube"
  log "Cluster  : $CLUSTER_NAME"
  log "VIP      : $CONTROL_PLANE_VIP:$CONTROL_PLANE_PORT"
  log "Nodes    : ${CP_IPS[*]}"
  log "Registry : $REGISTRY_IP"
}

# =============================================================================
# Phase 1 — SSH key generation and distribution
# =============================================================================
phase1_ssh_keys() {
  step "Phase 1: SSH key setup"

  # sshpass is needed only for initial key distribution
  if ! command -v sshpass &>/dev/null; then
    log "Installing sshpass..."
    sudo apt-get install -y -q sshpass || die "Cannot install sshpass — run: apt-get install -y sshpass"
  fi

  # Generate a dedicated deploy key if it doesn't exist
  if [[ ! -f "$SSH_KEY" ]]; then
    ssh-keygen -t rsa -b 4096 -f "$SSH_KEY" -N "" -C "nkp-deploy" -q
    log "Generated $SSH_KEY"
  else
    log "SSH key exists — skipping generation"
  fi

  # Copy key to every node — ssh-copy-id won't add duplicate entries
  for ip in "${CP_IPS[@]}"; do
    log "  → $ip"
    sshpass -p "$SSH_PASS" ssh-copy-id \
      -o StrictHostKeyChecking=no \
      -i "${SSH_KEY}.pub" \
      "$SSH_USER@$ip" 2>/dev/null \
    && log "    ✓" \
    || warn "    key copy returned non-zero (already installed or wrong password)"
  done
}

# =============================================================================
# Phase 2 — Node prerequisites on all CP nodes
# =============================================================================
phase2_node_prereqs() {
  step "Phase 2: Node prerequisites"

  for ip in "${CP_IPS[@]}"; do
    log "  Configuring $ip..."
    ssh_node "$ip" bash -s -- \
      "$REGISTRY_MIRROR_URL" <<'REMOTE'
set -e
MIRROR_SERVER="$1"

# ── disable swap ──────────────────────────────────────────────────────────────
swapoff -a 2>/dev/null || true
sed -i -E '/^[^#].*[[:space:]]swap[[:space:]]/s/^/#/' /etc/fstab

# ── kernel modules ────────────────────────────────────────────────────────────
cat > /etc/modules-load.d/nkp-k8s.conf <<'EOF'
overlay
br_netfilter
EOF
modprobe overlay      2>/dev/null || true
modprobe br_netfilter 2>/dev/null || true

# ── sysctl ────────────────────────────────────────────────────────────────────
cat > /etc/sysctl.d/99-nkp-k8s.conf <<'EOF'
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
fs.inotify.max_user_instances       = 8192
fs.inotify.max_user_watches         = 1048576
vm.overcommit_memory                = 1
EOF
sysctl --system >/dev/null 2>&1

# ── containerd: enable SystemdCgroup ─────────────────────────────────────────
mkdir -p /etc/containerd
if ! grep -q "SystemdCgroup = true" /etc/containerd/config.toml 2>/dev/null; then
  containerd config default 2>/dev/null > /etc/containerd/config.toml
  sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
fi

# ── containerd: _default catch-all mirror → local registry ───────────────────
# _default makes containerd route ALL registry pulls through the local mirror.
CERTS_DIR="/etc/containerd/certs.d"
mkdir -p "$CERTS_DIR/_default"
cat > "$CERTS_DIR/_default/hosts.toml" <<EOF
server = "${MIRROR_SERVER}"

[host."${MIRROR_SERVER}"]
  capabilities = ["pull", "resolve"]
  skip_verify = true
EOF

# ── containerd config: set config_path for hosts.toml to take effect ─────────
if ! grep -q "config_path" /etc/containerd/config.toml 2>/dev/null; then
  sed -i 's|^\(\s*\)\[plugins."io.containerd.grpc.v1.cri".registry\]|\1[plugins."io.containerd.grpc.v1.cri".registry]\n\1  config_path = "/etc/containerd/certs.d"|' \
    /etc/containerd/config.toml 2>/dev/null || true
fi

systemctl enable containerd  >/dev/null 2>&1 || true
systemctl restart containerd

echo "✓ $(hostname) ready"
REMOTE
    log "    ✓ $ip"
  done
}

# =============================================================================
# Phase 3 — Docker on bootstrap node (needed for kind bootstrap cluster)
# =============================================================================
phase3_push_bundles() {
  step "Phase 3: Push image bundles to local registry"
  # Docker must be pre-installed on the bootstrap node — air-gapped env cannot
  # pull Docker CE from the internet.
  docker info &>/dev/null || die "Docker not running on bootstrap node"

  log "Pushing Konvoy images (~10 GB)..."
  nkp push bundle \
    --bundle "$KONVOY_BUNDLE" \
    --to-registry "$REGISTRY_IP" \
    --registry-insecure-skip-tls-verify
  log "✓ Konvoy bundle pushed"

  log "Pushing Kommander images (~7 GB)..."
  nkp push bundle \
    --bundle "$KOMMANDER_BUNDLE" \
    --to-registry "$REGISTRY_IP" \
    --registry-insecure-skip-tls-verify
  log "✓ Kommander bundle pushed"
}

# =============================================================================
# Phase 4 — NKP bootstrap cluster (kind)
# =============================================================================
phase4_bootstrap() {
  step "Phase 4: NKP bootstrap cluster"
  if [[ -f "$KUBECONFIG_BOOTSTRAP" ]] && \
     kubectl --kubeconfig "$KUBECONFIG_BOOTSTRAP" get nodes &>/dev/null 2>&1; then
    log "Bootstrap cluster already running — skipping"
  else
    nkp create bootstrap \
      --registry-mirror-url "$REGISTRY_MIRROR_URL" \
      --registry-insecure-skip-tls-verify \
      --kubeconfig "$KUBECONFIG_BOOTSTRAP"
    log "✓ Bootstrap cluster ready"
  fi
}

# =============================================================================
# Phase 5 — PreprovisionedInventory (register CP node IPs into bootstrap)
# =============================================================================
phase5_inventory() {
  step "Phase 5: Node inventory"
  export KUBECONFIG="$KUBECONFIG_BOOTSTRAP"

  SSH_PUBKEY=$(cat "${SSH_KEY}.pub")
  local idx=0

  for ip in "${CP_IPS[@]}"; do
    local name="${CLUSTER_NAME}-cp-${idx}"

    if kubectl get preprovisionedinventory "$name" -n default &>/dev/null 2>&1; then
      log "  $name already registered — skipping"
    else
      kubectl apply -f - <<EOF
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: PreprovisionedInventory
metadata:
  name: ${name}
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
spec:
  primaryIP: ${ip}
  sshAuthorizedKeys:
    - "${SSH_PUBKEY}"
EOF
      log "  ✓ Registered $ip → $name"
    fi
    idx=$((idx + 1))
  done
}

# =============================================================================
# Phase 6 — Create NKP cluster
# =============================================================================
phase6_create_cluster() {
  step "Phase 6: Create NKP cluster"
  export KUBECONFIG="$KUBECONFIG_BOOTSTRAP"

  if kubectl get cluster "$CLUSTER_NAME" -n default &>/dev/null 2>&1; then
    log "Cluster $CLUSTER_NAME already exists — skipping"
    return
  fi

  nkp create cluster preprovisioned \
    --cluster-name                "$CLUSTER_NAME" \
    --control-plane-endpoint-host "$CONTROL_PLANE_VIP" \
    --control-plane-endpoint-port "$CONTROL_PLANE_PORT" \
    --control-plane-replicas      3 \
    --worker-replicas             0 \
    --ssh-username                "$SSH_USER" \
    --ssh-private-key-file        "$SSH_KEY" \
    --registry-mirror-url         "$REGISTRY_MIRROR_URL" \
    --registry-insecure-skip-tls-verify \
    --self-managed \
    --kubeconfig "$KUBECONFIG_BOOTSTRAP"

  log "✓ Cluster manifest applied"
}

# =============================================================================
# Phase 7 — Wait for cluster + export kubeconfig
# =============================================================================
phase7_wait() {
  step "Phase 7: Waiting for cluster (15-40 min depending on image pull speed)"
  export KUBECONFIG="$KUBECONFIG_BOOTSTRAP"

  if nkp wait cluster "$CLUSTER_NAME" \
       --namespace default \
       --timeout 60m \
       --kubeconfig "$KUBECONFIG_BOOTSTRAP" 2>/dev/null; then
    log "✓ nkp wait cluster complete"
  else
    # Fallback: watch CAPI cluster condition
    log "nkp wait unavailable — using kubectl watch (60m timeout)..."
    kubectl wait cluster "$CLUSTER_NAME" \
      -n default \
      --for=condition=Ready \
      --timeout=60m
  fi

  nkp get kubeconfig "$CLUSTER_NAME" \
    --namespace default \
    --kubeconfig "$KUBECONFIG_BOOTSTRAP" \
    > "$KUBECONFIG_CLUSTER"
  chmod 600 "$KUBECONFIG_CLUSTER"
  log "✓ Kubeconfig: $KUBECONFIG_CLUSTER"
}

# =============================================================================
# Phase 8 — Untaint control planes (required when no workers exist)
# =============================================================================
phase8_untaint_cp() {
  step "Phase 8: Untaint control plane nodes"
  export KUBECONFIG="$KUBECONFIG_CLUSTER"

  while IFS= read -r node; do
    kubectl taint node "$node" \
      node-role.kubernetes.io/control-plane:NoSchedule- \
      2>/dev/null \
    && log "  Untainted $node" \
    || log "  $node — taint already absent"
  done < <(kubectl get nodes -o name | sed 's|node/||')
}

# =============================================================================
# Phase 9 — MetalLB IP address pool
# =============================================================================
phase9_metallb() {
  step "Phase 9: MetalLB IP pool ($LB_IP_RANGE)"
  export KUBECONFIG="$KUBECONFIG_CLUSTER"

  if kubectl get ipaddresspool -n metallb-system nkp-pool &>/dev/null 2>&1; then
    log "MetalLB pool already configured — skipping"
    return
  fi

  kubectl apply -f - <<EOF
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nkp-pool
  namespace: metallb-system
spec:
  addresses:
    - ${LB_IP_RANGE}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: nkp-l2
  namespace: metallb-system
EOF
  log "✓ MetalLB pool applied"
}

# =============================================================================
# Phase 10 — Kommander trimmed install
# =============================================================================
phase10_kommander() {
  step "Phase 10: Kommander (trimmed)"
  export KUBECONFIG="$KUBECONFIG_CLUSTER"

  if kubectl get namespace kommander &>/dev/null 2>&1; then
    log "Kommander already installed — skipping"
    return
  fi

  # Only the core management apps; monitoring/logging/velero disabled.
  # Add entries here as needed for your environment.
  cat > /tmp/kommander-config.yaml <<'EOF'
apiVersion: config.kommander.mesosphere.io/v1alpha1
kind: Installation
apps:
  dex:
    enabled: true
  dex-k8s-authenticator:
    enabled: true
  external-secrets:
    enabled: false
  gatekeeper:
    enabled: false
  git-operator:
    enabled: true
  grafana-logging:
    enabled: false
  grafana-loki:
    enabled: false
  kommander:
    enabled: true
  kommander-ui:
    enabled: true
  kube-prometheus-stack:
    enabled: false
  kubefed:
    enabled: false
  kubernetes-dashboard:
    enabled: false
  kubetunnel:
    enabled: false
  logging-operator:
    enabled: false
  nkp-insights-management:
    enabled: false
  prometheus-adapter:
    enabled: false
  reloader:
    enabled: true
  rook-ceph:
    enabled: false
  rook-ceph-cluster:
    enabled: false
  traefik:
    enabled: true
    values: |
      service:
        annotations: {}
  traefik-forward-auth-mgmt:
    enabled: true
  velero:
    enabled: false
ageEncryptionSecretName: sops-age
clusterHostname: ""
airgapped:
  enabled: true
EOF

  nkp install kommander \
    --installer-config /tmp/kommander-config.yaml \
    --airgapped \
    --kubeconfig "$KUBECONFIG_CLUSTER"

  log "✓ Kommander installed"
}

# =============================================================================
# Phase 11 — Teardown bootstrap (cleanup after self-managed pivot)
# =============================================================================
phase11_teardown_bootstrap() {
  step "Phase 11: Teardown bootstrap cluster"
  if [[ ! -f "$KUBECONFIG_BOOTSTRAP" ]]; then
    log "Bootstrap kubeconfig gone — already torn down"
    return
  fi
  if kubectl --kubeconfig "$KUBECONFIG_BOOTSTRAP" \
       get cluster "$CLUSTER_NAME" -n default &>/dev/null 2>&1; then
    log "Cluster still on bootstrap — skipping teardown (pivot not complete yet?)"
    return
  fi
  nkp delete bootstrap \
    --kubeconfig "$KUBECONFIG_BOOTSTRAP" 2>/dev/null || true
  rm -f "$KUBECONFIG_BOOTSTRAP"
  log "✓ Bootstrap torn down"
}

# =============================================================================
# Phase 12 — Verify
# =============================================================================
phase12_verify() {
  step "Phase 12: Verify"
  export KUBECONFIG="$KUBECONFIG_CLUSTER"

  echo ""
  kubectl get nodes -o wide
  echo ""
  echo "Unhealthy pods (if any):"
  kubectl get pods -A --field-selector='status.phase!=Running,status.phase!=Succeeded' \
    2>/dev/null | head -20 || true

  echo ""
  log "✓ Deployment complete"
  log ""
  log "  Kubeconfig : export KUBECONFIG=$KUBECONFIG_CLUSTER"
  log "  Dashboard  : https://${CONTROL_PLANE_VIP}/dkp/kommander/dashboard"
  log ""

  local creds
  creds=$(kubectl -n kommander get secret dkp-credentials \
    -o jsonpath='{.data.password}' 2>/dev/null | base64 -d 2>/dev/null) || true
  if [[ -n "$creds" ]]; then
    log "  Admin pass : $creds"
  else
    log "  Admin pass : run 'nkp get dashboard --kubeconfig $KUBECONFIG_CLUSTER'"
  fi
}

# =============================================================================
# Main
# =============================================================================
main() {
  echo ""
  echo -e "${CYAN}${BOLD}╔══════════════════════════════════════════════════════╗"
  echo -e "║  NKP 2.17 — Air-Gapped 3-CP / 0-Worker Deploy       ║"
  echo -e "╚══════════════════════════════════════════════════════╝${NC}"
  echo ""

  phase0_preflight
  phase1_ssh_keys
  phase2_node_prereqs
  phase3_push_bundles
  phase4_bootstrap
  phase5_inventory
  phase6_create_cluster
  phase7_wait
  phase8_untaint_cp
  phase9_metallb
  phase10_kommander
  phase11_teardown_bootstrap
  phase12_verify
}

main "$@"
